### PR TITLE
Add fine grained settings for window management

### PR DESCRIPTION
**Pull request by pvdstel**
Adds additional settings for controlling if

- The desktop window is shown when the app is launched _because_ of the game launching.
- The in-game window is shown automatically, when the game launches while Minimap is running.

The in-game window is always shown if the app is launched due to the game launching.

image

### CODE REVIEW

**Comment by pvdstel** [comment]
Also added some optimizations for loading the chunks, and displaying content while the app loads.

**Comment by CptWesley** [comment]
Just a conceptual question. Why have these as explicit settings instead of just remembering the last configuration the user used?

**Comment by pvdstel** [comment]
Because there isn't necessarily a last configuration. Typically, the window configuration would be stored when the application closes. But in our case, there are no open windows when the application closes. I haven't really been able to come up with a scheme that handles this properly without weird edge cases since this was first requested. So I figured it might be best to implement it as toggles, so users can deterministically control which windows will open, and when.

The best way to handle it might be to only store window configurations (open/closed) while the game is running, but that would potentially be a pretty nasty change, with some unexpected behaviors.

**Comment by CptWesley** [comment]
Hmm fair enough. I didn't take into account the fact that application "lives" even when the game is off.

**Pull request merged**
