### PR TITLE
Adds Scrollable feature to desktop minimap.

### PR DESCRIPTION
**Pull request by yardik**
Allows for click-drag (similar to Google Maps)
Double-Click to re-center on your position
Not supported in compass mode / in-game overlay

### CODE REVIEW

**Comment by yardik** [comment]
> I'm not sure if the double-click to recenter is the most obvious control.

Agreed. Could add a clickable 're-center' button for this? Any preferences?

**Comment by CptWesley** [comment]
Cannot reproduce, both start instantly. Perhaps it's your browser?

**Comment by yardik** [comment]
> Nope! I mean that it should only start dragging after you've moved a couple of pixels. This could be done with a check in the `mouseMove` handler. If you're on desktop, scroll up the page and try to drag the GitHub logo, it'll take a few pixels before you actually drag it. And same with Google Maps; dragging only really starts after you've moved the cursor a few pixels while holding the button down.

I'll add this while I'm at it.. won't set dragged until you've moved at least 5px.

**Comment by yardik** [comment]
OK - all changes made. Check it out :)

**Comment by yardik** [comment]
Oh, this one isn't merged yet. Nevermind, I'll create a new one for the highlight.

**Pull request merged**
